### ISSUE TITLE
cheat not working in 2022.12.8 (latest version)

### ISSUE THREAD

**Issue by ForkliftJinx** [HackerHansen/AmongUsCosmetics#15] opened 2022-12-16 16:12 UTC
title says it all. i would be glad if you fixed it

**Comment by HackerHansen** [comment] 2022-12-16 16:19
Cool, thanks for letting me know. I'll fix it when I have time, probably later today or tomorrow

**Comment by ForkliftJinx** [comment] 2022-12-16 16:45
alright, a really fast response, thanks dude.
appreciate it.

**Comment by HackerHansen** [comment] 2022-12-18 03:04
Hey, I just updated my game and checked and everything seems to work fine on v2022.12.14. Can you update to that version and try again?

**Comment by ForkliftJinx** [comment] 2022-12-18 08:08
alright

**Comment by HackerHansen** [comment] 2022-12-19 03:07
lmk the results when you're able to

**Comment by Doredialilligan** [comment] 2022-12-19 08:05
It is not working in the last itch.io release. It only works on Steam releases or is not compatible at the moment?

**Comment by ForkliftJinx** [comment] 2022-12-19 18:30
oh yeah. exactly my problem with the program atm

**Comment by HackerHansen** [comment] 2022-12-20 19:27
Oh yeah, this is only for the steam version. It says so at the top of the readme, maybe I should add another message inside the program to make it more clear tho lol

Closing this issue for now since it seems to still work as intended on the steam version of the game

**Closed as completed by HackerHansen** 2022-12-20 19:27 UTC
